
 export const data = [
        {
            "id": "65de24c112361a5c40ce944f",
            "name": "mahsoor dal",
            "ten_gm": "",
            "fifty_gm": "",
            "hundered_gm": "",
            "quater_kg": "",
            "half_kg": "43",
            "one_kg": "85",
            "five_kg": "",
            "ten_kg": "",
            "twentyfive_kg": ""
        },
        {
            "id": "65de24e412361a5c40ce9450",
            "name": "chana dal",
            "ten_gm": "",
            "fifty_gm": "",
            "hundered_gm": "",
            "quater_kg": "",
            "half_kg": "42",
            "one_kg": "84",
            "five_kg": "",
            "ten_kg": "",
            "twentyfive_kg": ""
        },
        {
            "id": "65de256812361a5c40ce9451",
            "name": "rahar dal ",
            "ten_gm": "",
            "fifty_gm": "",
            "hundered_gm": "",
            "quater_kg": "",
            "half_kg": "85",
            "one_kg": "170",
            "five_kg": "",
            "ten_kg": "",
            "twentyfive_kg": ""
        },
        {
            "id": "65de259c12361a5c40ce9452",
            "name": "moong dal",
            "ten_gm": "",
            "fifty_gm": "",
            "hundered_gm": "",
            "quater_kg": "",
            "half_kg": "60",
            "one_kg": "120",
            "five_kg": "",
            "ten_kg": "",
            "twentyfive_kg": ""
        },
        {
            "id": "65de25b912361a5c40ce9453",
            "name": "kurthi dal",
            "ten_gm": "",
            "fifty_gm": "",
            "hundered_gm": "",
            "quater_kg": "",
            "half_kg": "40",
            "one_kg": "80",
            "five_kg": "",
            "ten_kg": "",
            "twentyfive_kg": ""
        },
        {
            "id": "65de25d612361a5c40ce9454",
            "name": "chana",
            "ten_gm": "",
            "fifty_gm": "",
            "hundered_gm": "",
            "quater_kg": "",
            "half_kg": "38",
            "one_kg": "76",
            "five_kg": "",
            "ten_kg": "",
            "twentyfive_kg": ""
        },
        {
            "id": "65de25fc12361a5c40ce9455",
            "name": "kabuli chana",
            "ten_gm": "",
            "fifty_gm": "",
            "hundered_gm": "",
            "quater_kg": "",
            "half_kg": "70",
            "one_kg": "140",
            "five_kg": "",
            "ten_kg": "",
            "twentyfive_kg": ""
        },
        {
            "id": "65de261112361a5c40ce9456",
            "name": "matar",
            "ten_gm": "",
            "fifty_gm": "",
            "hundered_gm": "",
            "quater_kg": "",
            "half_kg": "40",
            "one_kg": "80",
            "five_kg": "",
            "ten_kg": "",
            "twentyfive_kg": ""
        },
        {
            "id": "65de263212361a5c40ce9457",
            "name": "kushi matar",
            "ten_gm": "",
            "fifty_gm": "",
            "hundered_gm": "",
            "quater_kg": "",
            "half_kg": "35",
            "one_kg": "70",
            "five_kg": "",
            "ten_kg": "",
            "twentyfive_kg": ""
        },
        {
            "id": "65de32368eff57a6f65de489",
            "name": "sharda1",
            "ten_gm": "",
            "fifty_gm": "",
            "hundered_gm": "",
            "quater_kg": "",
            "half_kg": "",
            "one_kg": "",
            "five_kg": "",
            "ten_kg": "",
            "twentyfive_kg": "920"
        },
        {
            "id": "65de325b8eff57a6f65de48a",
            "name": "sharda2",
            "ten_gm": "",
            "fifty_gm": "",
            "hundered_gm": "",
            "quater_kg": "",
            "half_kg": "",
            "one_kg": "",
            "five_kg": "",
            "ten_kg": "",
            "twentyfive_kg": "1000"
        },
        {
            "id": "65de32998eff57a6f65de48b",
            "name": "aayog aata",
            "ten_gm": "",
            "fifty_gm": "",
            "hundered_gm": "",
            "quater_kg": "",
            "half_kg": "",
            "one_kg": "",
            "five_kg": "185",
            "ten_kg": "370",
            "twentyfive_kg": "1000"
        },
        {
            "id": "65de32d08eff57a6f65de48c",
            "name": "pushti aata",
            "ten_gm": "",
            "fifty_gm": "",
            "hundered_gm": "",
            "quater_kg": "",
            "half_kg": "",
            "one_kg": "",
            "five_kg": "",
            "ten_kg": "345",
            "twentyfive_kg": ""
        },
        {
            "id": "65de33778eff57a6f65de48d",
            "name": "hawai ghora oil",
            "ten_gm": "",
            "fifty_gm": "",
            "hundered_gm": "",
            "quater_kg": "",
            "half_kg": "",
            "one_kg": "130",
            "five_kg": "",
            "ten_kg": "",
            "twentyfive_kg": ""
        },
        {
            "id": "65de33d98eff57a6f65de48e",
            "name": "dalda oil",
            "ten_gm": "",
            "fifty_gm": "",
            "hundered_gm": "",
            "quater_kg": "",
            "half_kg": "",
            "one_kg": "125",
            "five_kg": "",
            "ten_kg": "",
            "twentyfive_kg": ""
        },
        {
            "id": "65de33f78eff57a6f65de48f",
            "name": "dalda refined",
            "ten_gm": "",
            "fifty_gm": "",
            "hundered_gm": "",
            "quater_kg": "",
            "half_kg": "",
            "one_kg": "110",
            "five_kg": "",
            "ten_kg": "",
            "twentyfive_kg": ""
        },
        {
            "id": "65de341b8eff57a6f65de490",
            "name": "sugar chini",
            "ten_gm": "",
            "fifty_gm": "",
            "hundered_gm": "",
            "quater_kg": "",
            "half_kg": "",
            "one_kg": "45",
            "five_kg": "",
            "ten_kg": "",
            "twentyfive_kg": ""
        },
        {
            "id": "65de346e8eff57a6f65de491",
            "name": "24 carat rice",
            "ten_gm": "",
            "fifty_gm": "",
            "hundered_gm": "",
            "quater_kg": "",
            "half_kg": "",
            "one_kg": "50",
            "five_kg": "",
            "ten_kg": "",
            "twentyfive_kg": ""
        },
        {
            "id": "65de34bc8eff57a6f65de492",
            "name": "bhagalpuri katarni rice",
            "ten_gm": "",
            "fifty_gm": "",
            "hundered_gm": "",
            "quater_kg": "",
            "half_kg": "",
            "one_kg": "65",
            "five_kg": "",
            "ten_kg": "",
            "twentyfive_kg": ""
        },
        {
            "id": "65de34e08eff57a6f65de493",
            "name": "arwa chawal rice",
            "ten_gm": "",
            "fifty_gm": "",
            "hundered_gm": "",
            "quater_kg": "",
            "half_kg": "",
            "one_kg": "55",
            "five_kg": "",
            "ten_kg": "",
            "twentyfive_kg": ""
        },
        {
            "id": "65de34ff8eff57a6f65de494",
            "name": "pista",
            "ten_gm": "",
            "fifty_gm": "",
            "hundered_gm": "",
            "quater_kg": "275",
            "half_kg": "",
            "one_kg": "",
            "five_kg": "",
            "ten_kg": "",
            "twentyfive_kg": ""
        },
        {
            "id": "65de35398eff57a6f65de495",
            "name": "kishmish",
            "ten_gm": "",
            "fifty_gm": "",
            "hundered_gm": "",
            "quater_kg": "70",
            "half_kg": "",
            "one_kg": "280",
            "five_kg": "",
            "ten_kg": "",
            "twentyfive_kg": ""
        },
        {
            "id": "65de35698eff57a6f65de496",
            "name": "kaju",
            "ten_gm": "",
            "fifty_gm": "",
            "hundered_gm": "",
            "quater_kg": "200",
            "half_kg": "",
            "one_kg": "",
            "five_kg": "",
            "ten_kg": "",
            "twentyfive_kg": ""
        },
        {
            "id": "65de35ae8eff57a6f65de497",
            "name": "almond badam",
            "ten_gm": "",
            "fifty_gm": "",
            "hundered_gm": "",
            "quater_kg": "190",
            "half_kg": "",
            "one_kg": "",
            "five_kg": "",
            "ten_kg": "",
            "twentyfive_kg": ""
        },
        {
            "id": "65de35f28eff57a6f65de498",
            "name": "moongfali badam",
            "ten_gm": "",
            "fifty_gm": "",
            "hundered_gm": "",
            "quater_kg": "37",
            "half_kg": "",
            "one_kg": "150",
            "five_kg": "",
            "ten_kg": "",
            "twentyfive_kg": ""
        },
        {
            "id": "65de36558eff57a6f65de499",
            "name": "munnaka",
            "ten_gm": "",
            "fifty_gm": "",
            "hundered_gm": "",
            "quater_kg": "125",
            "half_kg": "",
            "one_kg": "500",
            "five_kg": "",
            "ten_kg": "",
            "twentyfive_kg": ""
        },
        {
            "id": "65de36ae8eff57a6f65de49b",
            "name": "makahana",
            "ten_gm": "",
            "fifty_gm": "",
            "hundered_gm": "70",
            "quater_kg": "",
            "half_kg": "",
            "one_kg": "",
            "five_kg": "",
            "ten_kg": "",
            "twentyfive_kg": ""
        },
        {
            "id": "65de36ee8eff57a6f65de49c",
            "name": "anjeer",
            "ten_gm": "",
            "fifty_gm": "",
            "hundered_gm": "",
            "quater_kg": "300",
            "half_kg": "",
            "one_kg": "",
            "five_kg": "",
            "ten_kg": "",
            "twentyfive_kg": ""
        },
        {
            "id": "65de37248eff57a6f65de49d",
            "name": "khajur dates ",
            "ten_gm": "",
            "fifty_gm": "",
            "hundered_gm": "",
            "quater_kg": "",
            "half_kg": "160",
            "one_kg": "320",
            "five_kg": "",
            "ten_kg": "",
            "twentyfive_kg": ""
        },
        {
            "id": "65de37508eff57a6f65de49e",
            "name": "chuhara",
            "ten_gm": "",
            "fifty_gm": "",
            "hundered_gm": "",
            "quater_kg": "70",
            "half_kg": "",
            "one_kg": "",
            "five_kg": "",
            "ten_kg": "",
            "twentyfive_kg": ""
        },
        {
            "id": "65de37748eff57a6f65de49f",
            "name": "akhrot walnut",
            "ten_gm": "",
            "fifty_gm": "",
            "hundered_gm": "",
            "quater_kg": "275",
            "half_kg": "",
            "one_kg": "",
            "five_kg": "",
            "ten_kg": "",
            "twentyfive_kg": ""
        },
        {
            "id": "65de379c8eff57a6f65de4a0",
            "name": "mishri",
            "ten_gm": "",
            "fifty_gm": "",
            "hundered_gm": "10",
            "quater_kg": "",
            "half_kg": "",
            "one_kg": "",
            "five_kg": "",
            "ten_kg": "",
            "twentyfive_kg": ""
        },
        {
            "id": "65de37cd8eff57a6f65de4a1",
            "name": "pasta",
            "ten_gm": "",
            "fifty_gm": "",
            "hundered_gm": "",
            "quater_kg": "18",
            "half_kg": "35",
            "one_kg": "",
            "five_kg": "",
            "ten_kg": "",
            "twentyfive_kg": ""
        },
        {
            "id": "65de380a8eff57a6f65de4a2",
            "name": "machli chips fish 20",
            "ten_gm": "",
            "fifty_gm": "",
            "hundered_gm": "",
            "quater_kg": "",
            "half_kg": "",
            "one_kg": "",
            "five_kg": "",
            "ten_kg": "",
            "twentyfive_kg": ""
        },
        {
            "id": "65de383a8eff57a6f65de4a3",
            "name": "dalmot mixture don 85",
            "ten_gm": "",
            "fifty_gm": "",
            "hundered_gm": "",
            "quater_kg": "",
            "half_kg": "",
            "one_kg": "",
            "five_kg": "",
            "ten_kg": "",
            "twentyfive_kg": ""
        },
        {
            "id": "65de386d8eff57a6f65de4a4",
            "name": "peela pila sarso",
            "ten_gm": "",
            "fifty_gm": "",
            "hundered_gm": "12",
            "quater_kg": "",
            "half_kg": "",
            "one_kg": "",
            "five_kg": "",
            "ten_kg": "",
            "twentyfive_kg": ""
        },
        {
            "id": "65de38848eff57a6f65de4a5",
            "name": "kala sarso",
            "ten_gm": "",
            "fifty_gm": "",
            "hundered_gm": "10",
            "quater_kg": "",
            "half_kg": "",
            "one_kg": "",
            "five_kg": "",
            "ten_kg": "",
            "twentyfive_kg": ""
        },
        {
            "id": "65de389e8eff57a6f65de4a6",
            "name": "ajwain",
            "ten_gm": "",
            "fifty_gm": "",
            "hundered_gm": "35",
            "quater_kg": "",
            "half_kg": "",
            "one_kg": "",
            "five_kg": "",
            "ten_kg": "",
            "twentyfive_kg": ""
        },
        {
            "id": "65de38b88eff57a6f65de4a7",
            "name": "mangrela",
            "ten_gm": "",
            "fifty_gm": "",
            "hundered_gm": "36",
            "quater_kg": "",
            "half_kg": "",
            "one_kg": "",
            "five_kg": "",
            "ten_kg": "",
            "twentyfive_kg": ""
        },
        {
            "id": "65de38d18eff57a6f65de4a8",
            "name": "saunf",
            "ten_gm": "",
            "fifty_gm": "",
            "hundered_gm": "32",
            "quater_kg": "",
            "half_kg": "",
            "one_kg": "",
            "five_kg": "",
            "ten_kg": "",
            "twentyfive_kg": ""
        },
        {
            "id": "65de38e18eff57a6f65de4a9",
            "name": "methi",
            "ten_gm": "",
            "fifty_gm": "",
            "hundered_gm": "12",
            "quater_kg": "",
            "half_kg": "",
            "one_kg": "",
            "five_kg": "",
            "ten_kg": "",
            "twentyfive_kg": ""
        },
        {
            "id": "65de38fc8eff57a6f65de4aa",
            "name": "panchfouran",
            "ten_gm": "",
            "fifty_gm": "",
            "hundered_gm": "35",
            "quater_kg": "",
            "half_kg": "",
            "one_kg": "",
            "five_kg": "",
            "ten_kg": "",
            "twentyfive_kg": ""
        },
        {
            "id": "65de39228eff57a6f65de4ab",
            "name": "mareech",
            "ten_gm": "",
            "fifty_gm": "45",
            "hundered_gm": "90",
            "quater_kg": "",
            "half_kg": "",
            "one_kg": "",
            "five_kg": "",
            "ten_kg": "",
            "twentyfive_kg": ""
        },
        {
            "id": "65de396d8eff57a6f65de4ac",
            "name": "sukha mirchi",
            "ten_gm": "",
            "fifty_gm": "45",
            "hundered_gm": "30",
            "quater_kg": "75",
            "half_kg": "150",
            "one_kg": "300",
            "five_kg": "",
            "ten_kg": "",
            "twentyfive_kg": ""
        },
        {
            "id": "65de39918eff57a6f65de4ad",
            "name": "sawai 15",
            "ten_gm": "",
            "fifty_gm": "",
            "hundered_gm": "",
            "quater_kg": "",
            "half_kg": "",
            "one_kg": "",
            "five_kg": "",
            "ten_kg": "",
            "twentyfive_kg": ""
        },
        {
            "id": "65de39c68eff57a6f65de4ae",
            "name": "tezpatta tejpatta",
            "ten_gm": "",
            "fifty_gm": "10",
            "hundered_gm": "",
            "quater_kg": "",
            "half_kg": "",
            "one_kg": "",
            "five_kg": "",
            "ten_kg": "",
            "twentyfive_kg": ""
        },
        {
            "id": "65de39e38eff57a6f65de4af",
            "name": "papad 50",
            "ten_gm": "",
            "fifty_gm": "",
            "hundered_gm": "",
            "quater_kg": "",
            "half_kg": "",
            "one_kg": "",
            "five_kg": "",
            "ten_kg": "",
            "twentyfive_kg": ""
        }
    ]
